// Generated by Avro2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: fooBar.avsc
//          https://github.com/apache/avro/blob/main/share/test/schemas/fooBar.avsc
// Avro schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.avro {
    /**
        <see cref = 'Bar'/>
    */
    public interface fooBar {

        /**
        Avro record: example.avro.Bar
        */
        class Bar {
            string title;
            DateTime? created_at;
        }

        // ═════════════════════════ collection limits ═════════════════════════

        // Avro strings, bytes, arrays and maps are unbounded, AdHoc caps every collection at 255 by default.
        // This raises the file-wide cap; override a single field with [D(N)] / [D(+N)] where the real bound is known.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // either side may send any top-level record
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every top-level record of the schema, in both directions; nested records travel as sub-packs.
            [_____lr_____<Bar>]
            struct Exchange { }
        }

        // ═════════════════════════ Avro metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants attached
        // to the field. They live inside the project interface; the branches above list packs explicitly, so the
        // attribute classes never become packs.

        /** Avro default value: JSON scalars keep their type, complex defaults are JSON text. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } public DefaultAttribute(long value) { } public DefaultAttribute(double value) { } public DefaultAttribute(bool value) { } }

        /** Avro default value null. */
        public class DefaultNullAttribute : Attribute { }

        /** Avro logical type of the field (decimal carries precision and scale). */
        public class LogicalTypeAttribute : Attribute { public LogicalTypeAttribute(string name) { } public LogicalTypeAttribute(string name, long precision, long scale) { } }

        /** Avro sort order when it is not the default ascending. */
        public class OrderAttribute : Attribute { public OrderAttribute(string order) { } }

        /** Avro field aliases, comma separated. */
        public class AliasesAttribute : Attribute { public AliasesAttribute(string aliases) { } }

        /** The field holds a value of an Avro enum with fewer than two symbols (emitted as a constants container). */
        public class EnumRefAttribute : Attribute { public EnumRefAttribute(string container) { } }

        /** The Avro type name could not be resolved in this file; the payload is kept as raw bytes. */
        public class UnresolvedAttribute : Attribute { public UnresolvedAttribute(string avroType) { } }

    }
}
