// Generated by Avro2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: namespace.avpr
//          https://github.com/apache/avro/blob/main/share/test/schemas/namespace.avpr
// Avro protocol: TestNamespace (namespace org.apache.avro.test.namespace)
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.avro {
    /**
        <see cref = 'TestError'/>
        <see cref = 'TestRecord'/>
        <see cref = 'echo_Request'/>
        <see cref = 'error_Request'/>
        <see cref = 'error_Response'/>
    */
    public interface Namespace {

        /**
        Avro fixed: org.apache.avro.test.util.MD5
        */
        class MD5 { [D(16)] Binary[] TYPEDEF; }

        /**
        Avro record: org.apache.avro.test.namespace.TestRecord
        */
        class TestRecord {
            MD5 hash;
        }

        /**
        Avro error: org.apache.avro.test.errors.TestError
        */
        class TestError {
            string message;
        }

        // ═════════════════════════ RPC request / response packs ═════════════════════════

        /**
        Request of message echo
        */
        class echo_Request {
            TestRecord record;
        }

        /**
        Request of message error (no arguments)
        */
        class error_Request {
        }

        /**
        Response of message error (void: an empty acknowledgement)
        */
        class error_Response { }

        // ═════════════════════════ collection limits ═════════════════════════

        // Avro strings, bytes, arrays and maps are unbounded, AdHoc caps every collection at 255 by default.
        // This raises the file-wide cap; override a single field with [D(N)] / [D(+N)] where the real bound is known.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // calls the protocol messages
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // answers them
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            (L____________, TestRecord) echo(echo_Request req);
            (L____________, error_Response, TestError) error(error_Request req);
        }

        // ═════════════════════════ Avro metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants attached
        // to the field. They live inside the project interface; the branches above list packs explicitly, so the
        // attribute classes never become packs.

        /** Avro default value: JSON scalars keep their type, complex defaults are JSON text. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } public DefaultAttribute(long value) { } public DefaultAttribute(double value) { } public DefaultAttribute(bool value) { } }

        /** Avro default value null. */
        public class DefaultNullAttribute : Attribute { }

        /** Avro logical type of the field (decimal carries precision and scale). */
        public class LogicalTypeAttribute : Attribute { public LogicalTypeAttribute(string name) { } public LogicalTypeAttribute(string name, long precision, long scale) { } }

        /** Avro sort order when it is not the default ascending. */
        public class OrderAttribute : Attribute { public OrderAttribute(string order) { } }

        /** Avro field aliases, comma separated. */
        public class AliasesAttribute : Attribute { public AliasesAttribute(string aliases) { } }

        /** The field holds a value of an Avro enum with fewer than two symbols (emitted as a constants container). */
        public class EnumRefAttribute : Attribute { public EnumRefAttribute(string container) { } }

        /** The Avro type name could not be resolved in this file; the payload is kept as raw bytes. */
        public class UnresolvedAttribute : Attribute { public UnresolvedAttribute(string avroType) { } }

    }
}
