// Generated by Avro2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: SchemaBuilder.avsc
//          https://github.com/apache/avro/blob/main/lang/java/avro/src/test/resources/SchemaBuilder.avsc
// Avro schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.avro {
    /**
        <see cref = 'nestedOptionalRecord'/>
        <see cref = 'nestedOptionalRecordWithDefault'/>
        <see cref = 'nestedRequiredRecord'/>
        <see cref = 'nestedUnionRecordWithDefault'/>
        <see cref = 'recordAll'/>
        <see cref = 'recordAll_unionArrayWithDefault_union'/>
        <see cref = 'recordAll_unionBooleanWithDefault_union'/>
        <see cref = 'recordAll_unionBytesWithDefault_union'/>
        <see cref = 'recordAll_unionDoubleWithDefault_union'/>
        <see cref = 'recordAll_unionEnumWithDefault_union'/>
        <see cref = 'recordAll_unionFixedWithDefault_union'/>
        <see cref = 'recordAll_unionFloatWithDefault_union'/>
        <see cref = 'recordAll_unionLongWithDefault_union'/>
        <see cref = 'recordAll_unionMapWithDefault_union'/>
        <see cref = 'recordAll_unionRecordWithDefault_union'/>
        <see cref = 'recordAll_unionStringWithDefault_union'/>
    */
    public interface SchemaBuilder {

        /**
        Avro record: recordAll
        */
        class recordAll {
            bool requiredBoolean;
            [Default(true)] bool requiredBooleanWithDefault;
            [DefaultNull] bool? optionalBoolean;
            [Default(true)] bool? optionalBooleanWithDefault;
            [X] int requiredInt;
            [X, DefaultNull] int? optionalInt;
            [X, Default(1)] int? optionalIntWithDefault;
            [X] long requiredLong;
            [X, DefaultNull] long? optionalLong;
            [X, Default(1)] long? optionalLongWithDefault;
            float requiredFloat;
            [DefaultNull] float? optionalFloat;
            [Default(1)] float? optionalFloatWithDefault;
            double requiredDouble;
            [DefaultNull] double? optionalDouble;
            [Default(1)] double? optionalDoubleWithDefault;
            Binary[,,] requiredBytes;
            [DefaultNull] Binary[,,] optionalBytes;
            [Default("A")] Binary[,,] optionalBytesWithDefault;
            string requiredString;
            [DefaultNull] string optionalString;
            [Default("a")] string optionalStringWithDefault;
            nestedRequiredRecord requiredRecord;
            [DefaultNull] nestedOptionalRecord optionalRecord;
            [Default("{\"nestedRequiredBoolean\":true}")] nestedOptionalRecordWithDefault optionalRecordWithDefault;
            requiredEnum requiredEnum;
            [DefaultNull] optionalEnum? optionalEnum;
            [Default("b")] optionalEnumWithDefault? optionalEnumWithDefault;
            string[,,] requiredArray;
            [DefaultNull] string[,,] optionalArray;
            [Default("[\"a\"]")] string[,,] optionalArrayWithDefault;
            Map<string, string> requiredMap;
            [DefaultNull] Map<string, string> optionalMap;
            [Default("{\"a\":\"b\"}")] Map<string, string> optionalMapWithDefault;
            requiredFixed requiredFixed;
            [DefaultNull] optionalFixed optionalFixed;
            [Default("A")] optionalFixedWithDefault optionalFixedWithDefault;
            [X] long? unionType;
            [Default(true)] recordAll_unionBooleanWithDefault_union unionBooleanWithDefault;
            [X, Default(1)] int? unionIntWithDefault;
            [Default(1)] recordAll_unionLongWithDefault_union unionLongWithDefault;
            [Default(1)] recordAll_unionFloatWithDefault_union unionFloatWithDefault;
            [Default(1)] recordAll_unionDoubleWithDefault_union unionDoubleWithDefault;
            [Default("A")] recordAll_unionBytesWithDefault_union unionBytesWithDefault;
            [Default("a")] recordAll_unionStringWithDefault_union unionStringWithDefault;
            [Default("{\"nestedRequiredBoolean\":true}")] recordAll_unionRecordWithDefault_union unionRecordWithDefault;
            [Default("b")] recordAll_unionEnumWithDefault_union unionEnumWithDefault;
            [Default("[\"a\"]")] recordAll_unionArrayWithDefault_union unionArrayWithDefault;
            [Default("{\"a\":\"b\"}")] recordAll_unionMapWithDefault_union unionMapWithDefault;
            [Default("A")] recordAll_unionFixedWithDefault_union unionFixedWithDefault;
        }

        /**
        Avro record: nestedRequiredRecord
        */
        class nestedRequiredRecord {
            bool nestedRequiredBoolean;
        }

        /**
        Avro record: nestedOptionalRecord
        */
        class nestedOptionalRecord {
            bool nestedRequiredBoolean;
        }

        /**
        Avro record: nestedOptionalRecordWithDefault
        */
        class nestedOptionalRecordWithDefault {
            bool nestedRequiredBoolean;
        }

        /**
        Avro enum: requiredEnum
        */
        enum requiredEnum {
            a,
            b,
        }

        /**
        Avro enum: optionalEnum
        */
        enum optionalEnum {
            a,
            b,
        }

        /**
        Avro enum: optionalEnumWithDefault
        */
        enum optionalEnumWithDefault {
            a,
            b,
        }

        /**
        Avro fixed: requiredFixed
        */
        class requiredFixed { [D(1)] Binary[] TYPEDEF; }

        /**
        Avro fixed: optionalFixed
        */
        class optionalFixed { [D(1)] Binary[] TYPEDEF; }

        /**
        Avro fixed: optionalFixedWithDefault
        */
        class optionalFixedWithDefault { [D(1)] Binary[] TYPEDEF; }

        /**
        Avro record: nestedUnionRecordWithDefault
        */
        class nestedUnionRecordWithDefault {
            bool nestedRequiredBoolean;
        }

        /**
        Avro enum: nestedUnionEnumWithDefault
        */
        enum nestedUnionEnumWithDefault {
            a,
            b,
        }

        /**
        Avro fixed: nestedUnionFixedWithDefault
        */
        class nestedUnionFixedWithDefault { [D(1)] Binary[] TYPEDEF; }

        // ═════════════════════════ union packs: one optional field per alternative ═════════════════════════

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionBooleanWithDefault_union {
            bool? Boolean;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionLongWithDefault_union {
            [X] long? Long;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionFloatWithDefault_union {
            float? Float;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionDoubleWithDefault_union {
            double? Double;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionBytesWithDefault_union {
            Binary[,,] bytes;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionStringWithDefault_union {
            string String;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionRecordWithDefault_union {
            nestedUnionRecordWithDefault nestedUnionRecordWithDefault;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionEnumWithDefault_union {
            nestedUnionEnumWithDefault? nestedUnionEnumWithDefault;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionArrayWithDefault_union {
            string[,,] array_of_string;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionMapWithDefault_union {
            Map<string, string> map_of_string;
            [X] int? Int;
        }

        /** Avro union: exactly one of the fields is set. */
        class recordAll_unionFixedWithDefault_union {
            nestedUnionFixedWithDefault nestedUnionFixedWithDefault;
            [X] int? Int;
        }

        // ═════════════════════════ collection limits ═════════════════════════

        // Avro strings, bytes, arrays and maps are unbounded, AdHoc caps every collection at 255 by default.
        // This raises the file-wide cap; override a single field with [D(N)] / [D(+N)] where the real bound is known.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // either side may send any top-level record
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every top-level record of the schema, in both directions; nested records travel as sub-packs.
            [_____lr_____<recordAll>]
            struct Exchange { }
        }

        // ═════════════════════════ Avro metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants attached
        // to the field. They live inside the project interface; the branches above list packs explicitly, so the
        // attribute classes never become packs.

        /** Avro default value: JSON scalars keep their type, complex defaults are JSON text. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } public DefaultAttribute(long value) { } public DefaultAttribute(double value) { } public DefaultAttribute(bool value) { } }

        /** Avro default value null. */
        public class DefaultNullAttribute : Attribute { }

        /** Avro logical type of the field (decimal carries precision and scale). */
        public class LogicalTypeAttribute : Attribute { public LogicalTypeAttribute(string name) { } public LogicalTypeAttribute(string name, long precision, long scale) { } }

        /** Avro sort order when it is not the default ascending. */
        public class OrderAttribute : Attribute { public OrderAttribute(string order) { } }

        /** Avro field aliases, comma separated. */
        public class AliasesAttribute : Attribute { public AliasesAttribute(string aliases) { } }

        /** The field holds a value of an Avro enum with fewer than two symbols (emitted as a constants container). */
        public class EnumRefAttribute : Attribute { public EnumRefAttribute(string container) { } }

        /** The Avro type name could not be resolved in this file; the payload is kept as raw bytes. */
        public class UnresolvedAttribute : Attribute { public UnresolvedAttribute(string avroType) { } }

    }
}
