// Generated by Avro2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: simple.avpr
//          https://github.com/apache/avro/blob/main/share/test/schemas/simple.avpr
// Avro protocol: Simple (namespace org.apache.avro.test)
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.avro {
    /**
        <see cref = 'TestError'/>
        <see cref = 'TestRecord'/>
        <see cref = 'TestRecordWithUnion'/>
        <see cref = 'ack_Request'/>
        <see cref = 'add_Request'/>
        <see cref = 'add_Response'/>
        <see cref = 'echoBytes_Request'/>
        <see cref = 'echoBytes_Response'/>
        <see cref = 'echo_Request'/>
        <see cref = 'error_Request'/>
        <see cref = 'error_Response'/>
        <see cref = 'hello_Request'/>
        <see cref = 'hello_Response'/>
    */
    public interface simple {
        // ═════════════════════════ protocol Simple ═════════════════════════
        /**
        Protocol used for testing.
        */


        /**
        Avro enum: org.apache.avro.test.Kind
        */
        enum Kind {
            FOO,
            BAR,
            BAZ,
        }

        /**
        Avro fixed: org.apache.avro.test.MD5
        */
        class MD5 { [D(16)] Binary[] TYPEDEF; }

        /**
        Avro record: org.apache.avro.test.TestRecord
        */
        class TestRecord {
            [Order("ignore")] string name;
            [Order("descending")] Kind kind;
            MD5 hash;
        }

        /**
        Avro error: org.apache.avro.test.TestError
        */
        class TestError {
            string message;
        }

        /**
        Avro record: org.apache.avro.test.TestRecordWithUnion
        */
        class TestRecordWithUnion {
            Kind? kind;
            string value;
        }

        // ═════════════════════════ RPC request / response packs ═════════════════════════

        /**
        Send a greeting
        Request of message hello
        */
        class hello_Request {
            [Aliases("salute")] string greeting;
        }

        /**
        Response of message hello
        */
        class hello_Response { string value; }

        /**
        Pretend you're in a cave!
        Request of message echo
        */
        class echo_Request {
            TestRecord record;
        }

        /**
        Request of message add
        */
        class add_Request {
            [X] int arg1;
            [X] int arg2;
        }

        /**
        Response of message add
        */
        class add_Response { [X] int value; }

        /**
        Request of message echoBytes
        */
        class echoBytes_Request {
            Binary[,,] data;
        }

        /**
        Response of message echoBytes
        */
        class echoBytes_Response { Binary[,,] value; }

        /**
        Always throws an error.
        Request of message error (no arguments)
        */
        class error_Request {
        }

        /**
        Response of message error (void: an empty acknowledgement)
        */
        class error_Response { }

        /**
        Send a one way message
        Request of message ack (no arguments)
        */
        class ack_Request {
        }

        // ═════════════════════════ collection limits ═════════════════════════

        // Avro strings, bytes, arrays and maps are unbounded, AdHoc caps every collection at 255 by default.
        // This raises the file-wide cap; override a single field with [D(N)] / [D(+N)] where the real bound is known.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // calls the protocol messages
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // answers them
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Send a greeting
            (L____________, hello_Response) hello(hello_Request req);
            // Pretend you're in a cave!
            (L____________, TestRecord) echo(echo_Request req);
            (L____________, add_Response) add(add_Request req);
            (L____________, echoBytes_Response) echoBytes(echoBytes_Request req);
            // Always throws an error.
            (L____________, error_Response, TestError) error(error_Request req);
            // one-way messages: fire-and-forget from the client
            [l____________<ack_Request>]
            struct OneWay { }
        }

        // ═════════════════════════ Avro metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants attached
        // to the field. They live inside the project interface; the branches above list packs explicitly, so the
        // attribute classes never become packs.

        /** Avro default value: JSON scalars keep their type, complex defaults are JSON text. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } public DefaultAttribute(long value) { } public DefaultAttribute(double value) { } public DefaultAttribute(bool value) { } }

        /** Avro default value null. */
        public class DefaultNullAttribute : Attribute { }

        /** Avro logical type of the field (decimal carries precision and scale). */
        public class LogicalTypeAttribute : Attribute { public LogicalTypeAttribute(string name) { } public LogicalTypeAttribute(string name, long precision, long scale) { } }

        /** Avro sort order when it is not the default ascending. */
        public class OrderAttribute : Attribute { public OrderAttribute(string order) { } }

        /** Avro field aliases, comma separated. */
        public class AliasesAttribute : Attribute { public AliasesAttribute(string aliases) { } }

        /** The field holds a value of an Avro enum with fewer than two symbols (emitted as a constants container). */
        public class EnumRefAttribute : Attribute { public EnumRefAttribute(string container) { } }

        /** The Avro type name could not be resolved in this file; the payload is kept as raw bytes. */
        public class UnresolvedAttribute : Attribute { public UnresolvedAttribute(string avroType) { } }

    }
}
