// Generated by Avro2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: TestRecordWithLogicalTypes.avsc
//          https://github.com/apache/avro/blob/main/lang/java/avro/src/test/resources/TestRecordWithLogicalTypes.avsc
// Avro schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.avro {
    /**
        <see cref = 'TestRecordWithLogicalTypes'/>
    */
    public interface TestRecordWithLogicalTypesSchema {

        /**
        Schema for TestRecordWithLogicalTypes and TestRecordWithoutLogicalTypes, see TestSpecificLogicalTypes
        Avro record: org.apache.avro.specific.TestRecordWithLogicalTypes
        */
        class TestRecordWithLogicalTypes {
            bool b;
            [X] int i32;
            [X] long i64;
            float f32;
            double f64;
            [DefaultNull] string s;
            DaysSinceEpoch d;
            TimeOfDayMillis t;
            DateTime ts;
            [LogicalType("big-decimal")] Binary[,,] bd;
        }

        // ═════════════════════════ time types ═════════════════════════

        // Avro stores these as plain integers; AdHoc has first-class time types, so the raw number never
        // reaches the generated API and the wire carries only the bits the declared range needs.

        /** Avro logical type `date`: days since 1970-01-01, no time of day. */
        class DaysSinceEpoch : DateTimeDef {
            public DateTime min       => new DateTime(1970, 1, 1);
            public TimeSpan precision => TimeSpan.FromDays(1);
        }

        /** Avro logical type `time-millis`: milliseconds after midnight, 0 .. 86 399 999. */
        class TimeOfDayMillis : Duration {
            public long     max       => 86_400_000;
            public TimeSpan precision => TimeSpan.FromMilliseconds(1);
        }

        // ═════════════════════════ collection limits ═════════════════════════

        // Avro strings, bytes, arrays and maps are unbounded, AdHoc caps every collection at 255 by default.
        // This raises the file-wide cap; override a single field with [D(N)] / [D(+N)] where the real bound is known.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // either side may send any top-level record
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every top-level record of the schema, in both directions; nested records travel as sub-packs.
            [_____lr_____<TestRecordWithLogicalTypes>]
            struct Exchange { }
        }

        // ═════════════════════════ Avro metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator carries each one into the generated code as constants attached
        // to the field. They live inside the project interface; the branches above list packs explicitly, so the
        // attribute classes never become packs.

        /** Avro default value: JSON scalars keep their type, complex defaults are JSON text. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } public DefaultAttribute(long value) { } public DefaultAttribute(double value) { } public DefaultAttribute(bool value) { } }

        /** Avro default value null. */
        public class DefaultNullAttribute : Attribute { }

        /** Avro logical type of the field (decimal carries precision and scale). */
        public class LogicalTypeAttribute : Attribute { public LogicalTypeAttribute(string name) { } public LogicalTypeAttribute(string name, long precision, long scale) { } }

        /** Avro sort order when it is not the default ascending. */
        public class OrderAttribute : Attribute { public OrderAttribute(string order) { } }

        /** Avro field aliases, comma separated. */
        public class AliasesAttribute : Attribute { public AliasesAttribute(string aliases) { } }

        /** The field holds a value of an Avro enum with fewer than two symbols (emitted as a constants container). */
        public class EnumRefAttribute : Attribute { public EnumRefAttribute(string container) { } }

        /** The Avro type name could not be resolved in this file; the payload is kept as raw bytes. */
        public class UnresolvedAttribute : Attribute { public UnresolvedAttribute(string avroType) { } }

    }
}
